#!/usr/bin/env python3

import maps

def main():
    parser = maps.get_parser()
    args = parser.parse_args()
    output = maps.process(args)
    print('The output is in file %s' % output)



if __name__ == '__main__':
    main()
