#!/usr/bin/env python3

import maps

def main():
    parser = maps.get_parser()
    args = parser.parse_args()
    output = maps.process(args)
    print('The output is in file %s' % output)



if __name__ == '__main__':
    main()

# Para el futuro querría:
#
# * Añadir un interfaz gráfico decente.
# * Barra de progreso mientras escribe el fichero.
# * Hacer un preview de las imágenes de los mapas cuando se seleccionan.
# * Presentar estadísticas de desviación típica, componentes de Fourier y
#   similares, según el canal elegido para extraer la elevación.
# * Añadir un modo de selección de canal automático, según lo que parece más
#   prometedor por las estadísticas de la imagen.
# * Permitir abrir el resultado en meshlab o en blender si están disponibles.
# * Documentar el algoritmo que he escrito para conectar los puntos en triángulos
#   de la esfera.
